api_platform:
    eager_loading:
        fetch_partial: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page: 100 #TODO correct this

    http_cache:
        invalidation:
        enabled: true
        max_age: 0
        varnish_urls: ['%env(VARNISH_URL)%']
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true

    title: 'HaiUrca API'
    description: 'API'