api_platform:
    eager_loading:
        fetch_partial: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page: 100 #TODO correct this

    title: 'HaiUrca API'
    description: 'API'